services:
    app:
        build: .
        container_name: inventory
        ports:
            - "9001:8000"
        volumes:
            - .:/var/www/html
        networks:
            - inventory_laravel5
        depends_on:
            - db
        command: 'init.sh'

    db:
        build: db
        container_name: inventory_db
        ports:
            - "33976:3306"
        environment:
            MYSQL_ROOT_PASSWORD: password9
            MYSQL_DATABASE: inventory
        volumes:
            - inventory:/var/lib/mysql
        networks:
            - inventory_laravel5

volumes:
    inventory:
        driver: local

networks:
    inventory_laravel5:
        external: true